"""Shell hook generator for auto-stamping AI CLI tool output.

Usage::

    # Add to ~/.zshrc or ~/.bashrc:
    eval "$(akf shell-hook)"

    # Now any files created/modified by AI CLI tools get auto-stamped:
    claude "Write a Python script" > script.py   # → auto-stamped
    chatgpt "Summarize this doc" > summary.md    # → auto-stamped
    aider --message "Add tests"                  # → modified files stamped

The hook works by:
1. Before each command: if the command invokes a known AI tool,
   snapshot file mtimes in watched directories
2. After the command: find new/modified files and stamp them
"""

from __future__ import annotations

import os
import textwrap
from pathlib import Path

# AI CLI tools we recognize
AI_CLI_TOOLS = [
    "claude",
    "chatgpt",
    "sgpt",
    "aider",
    "ollama",
    "llm",
    "gh copilot",
    "copilot",
    "fabric",
    "mods",
    "tgpt",
    "manus",
]

# File extensions to stamp (mirrors watch.py SUPPORTED_EXTENSIONS)
WATCHED_EXTENSIONS = (
    "docx", "xlsx", "pptx", "pdf", "html", "htm",
    "json", "md", "markdown", "png", "jpg", "jpeg",
    "py", "js", "ts", "eml", "csv", "txt",
)


def _tool_pattern() -> str:
    """Build a shell regex pattern matching AI CLI tool invocations."""
    # Escape for shell regex; handle multi-word tools
    escaped = []
    for tool in AI_CLI_TOOLS:
        escaped.append(tool.replace(" ", "[[:space:]]"))
    return "|".join(escaped)


def generate_zsh_hook() -> str:
    """Generate zsh shell hook code."""
    tool_pattern = _tool_pattern()
    extensions = " ".join(f"*.{ext}" for ext in WATCHED_EXTENSIONS)

    return textwrap.dedent(f'''\
        # ── AKF Shell Hook (zsh) ──────────────────────────────────
        # Auto-stamps files created/modified by AI CLI tools.
        # Generated by: akf shell-hook

        _akf_marker_file="/tmp/.akf_shell_marker_$$"

        _akf_watched_dirs() {{
            local dirs=()
            if command -v akf >/dev/null 2>&1; then
                # Try to read dirs from watch config
                local cfg="$HOME/.akf/watch.json"
                if [[ -f "$cfg" ]]; then
                    dirs=($(python3 -c "
import json, os
try:
    cfg = json.load(open('$cfg'))
    for d in cfg.get('directories', []):
        print(os.path.expanduser(d))
except: pass
" 2>/dev/null))
                fi
            fi
            # Fallback to defaults
            if [[ ${{#dirs[@]}} -eq 0 ]]; then
                dirs=("$HOME/Downloads" "$HOME/Desktop" "$HOME/Documents")
            fi
            # Filter to existing directories
            local existing=()
            for d in "${{dirs[@]}}"; do
                [[ -d "$d" ]] && existing+=("$d")
            done
            echo "${{existing[@]}}"
        }}

        _akf_preexec() {{
            local cmd="$1"
            # Check if command invokes a known AI CLI tool
            if [[ "$cmd" =~ ^[[:space:]]*(sudo[[:space:]]+)?({tool_pattern}) ]]; then
                export _AKF_AI_CMD="$cmd"
                touch "$_akf_marker_file"
            fi
        }}

        _akf_precmd() {{
            # Only run if an AI command was tracked
            [[ -z "$_AKF_AI_CMD" ]] && return
            [[ ! -f "$_akf_marker_file" ]] && return

            local cmd="$_AKF_AI_CMD"
            unset _AKF_AI_CMD

            # Find files newer than our marker in watched directories
            local dirs
            dirs=($(_akf_watched_dirs))

            for dir in "${{dirs[@]}}"; do
                [[ -d "$dir" ]] || continue
                find "$dir" -maxdepth 3 -newer "$_akf_marker_file" \\
                    -type f \\( {" -o ".join(f'-name "{ext}"' for ext in (f"*.{e}" for e in WATCHED_EXTENSIONS))} \\) \\
                    ! -name ".*" ! -name "*.akf" 2>/dev/null | while IFS= read -r f; do
                    akf stamp "$f" --ai 2>/dev/null && \\
                        echo "\\033[0;36m[akf]\\033[0m Stamped: $f"
                done
            done

            # Also stamp files in current directory that changed
            find . -maxdepth 1 -newer "$_akf_marker_file" \\
                -type f \\( {" -o ".join(f'-name "{ext}"' for ext in (f"*.{e}" for e in WATCHED_EXTENSIONS))} \\) \\
                ! -name ".*" ! -name "*.akf" 2>/dev/null | while IFS= read -r f; do
                akf stamp "$f" --ai 2>/dev/null && \\
                    echo "\\033[0;36m[akf]\\033[0m Stamped: $f"
            done

            rm -f "$_akf_marker_file"
        }}

        # Register hooks
        autoload -Uz add-zsh-hook 2>/dev/null
        if (( $+functions[add-zsh-hook] )); then
            add-zsh-hook preexec _akf_preexec
            add-zsh-hook precmd _akf_precmd
        fi

        # Cleanup on shell exit
        _akf_cleanup() {{
            rm -f "$_akf_marker_file"
        }}
        add-zsh-hook zshexit _akf_cleanup 2>/dev/null
        # ── End AKF Shell Hook ────────────────────────────────────
    ''')


def generate_bash_hook() -> str:
    """Generate bash shell hook code."""
    tool_pattern = _tool_pattern()
    extensions = " ".join(f"*.{ext}" for ext in WATCHED_EXTENSIONS)

    return textwrap.dedent(f'''\
        # ── AKF Shell Hook (bash) ─────────────────────────────────
        # Auto-stamps files created/modified by AI CLI tools.
        # Generated by: akf shell-hook

        _akf_marker_file="/tmp/.akf_shell_marker_$$"

        _akf_watched_dirs() {{
            local cfg="$HOME/.akf/watch.json"
            if [[ -f "$cfg" ]] && command -v python3 >/dev/null 2>&1; then
                python3 -c "
import json, os
try:
    cfg = json.load(open('$cfg'))
    for d in cfg.get('directories', []):
        p = os.path.expanduser(d)
        if os.path.isdir(p): print(p)
except: pass
" 2>/dev/null
            else
                for d in "$HOME/Downloads" "$HOME/Desktop" "$HOME/Documents"; do
                    [[ -d "$d" ]] && echo "$d"
                done
            fi
        }}

        _akf_preexec_handler() {{
            local cmd="$1"
            if [[ "$cmd" =~ ^[[:space:]]*(sudo[[:space:]]+)?({tool_pattern}) ]]; then
                export _AKF_AI_CMD="$cmd"
                touch "$_akf_marker_file"
            fi
        }}

        _akf_precmd_handler() {{
            [[ -z "$_AKF_AI_CMD" ]] && return
            [[ ! -f "$_akf_marker_file" ]] && return

            unset _AKF_AI_CMD

            while IFS= read -r dir; do
                [[ -d "$dir" ]] || continue
                find "$dir" -maxdepth 3 -newer "$_akf_marker_file" \\
                    -type f \\( {" -o ".join(f'-name "{ext}"' for ext in (f"*.{e}" for e in WATCHED_EXTENSIONS))} \\) \\
                    ! -name ".*" ! -name "*.akf" 2>/dev/null | while IFS= read -r f; do
                    akf stamp "$f" --ai 2>/dev/null && \\
                        echo -e "\\033[0;36m[akf]\\033[0m Stamped: $f"
                done
            done < <(_akf_watched_dirs)

            # Current directory
            find . -maxdepth 1 -newer "$_akf_marker_file" \\
                -type f \\( {" -o ".join(f'-name "{ext}"' for ext in (f"*.{e}" for e in WATCHED_EXTENSIONS))} \\) \\
                ! -name ".*" ! -name "*.akf" 2>/dev/null | while IFS= read -r f; do
                akf stamp "$f" --ai 2>/dev/null && \\
                    echo -e "\\033[0;36m[akf]\\033[0m Stamped: $f"
            done

            rm -f "$_akf_marker_file"
        }}

        # Use bash-preexec if available, otherwise use DEBUG trap
        if [[ -n "${{bash_preexec_imported:-}}" ]] || \\
           declare -F __bp_preexec_invoke_exec >/dev/null 2>&1; then
            preexec_functions+=(_akf_preexec_handler)
            precmd_functions+=(_akf_precmd_handler)
        else
            trap '_akf_preexec_handler "$BASH_COMMAND"' DEBUG
            PROMPT_COMMAND="_akf_precmd_handler;${{PROMPT_COMMAND:-}}"
        fi

        # Cleanup
        trap 'rm -f "$_akf_marker_file"' EXIT
        # ── End AKF Shell Hook ────────────────────────────────────
    ''')


def generate_shell_hook(shell: str = "auto") -> str:
    """Generate shell hook code for the detected or specified shell.

    Args:
        shell: "zsh", "bash", or "auto" (detect from $SHELL).

    Returns:
        Shell code string to be eval'd.
    """
    if shell == "auto":
        user_shell = os.environ.get("SHELL", "")
        if "zsh" in user_shell:
            shell = "zsh"
        else:
            shell = "bash"

    if shell == "zsh":
        return generate_zsh_hook()
    return generate_bash_hook()
